name: pocketpedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  fonts:
  - family: DMSans
    fonts: 
    - asset: assets/DMSans.ttf
  assets:
    - assets/docs.png
    - assets/logo.png
    - assets/externals/apple.png
    - assets/externals/facebook.png
    - assets/externals/google.png
    - assets/material/login_divider.png
    - assets/navbar/cart.png
    - assets/navbar/home.png
    - assets/navbar/search.png
    - assets/navbar/user.png
    - assets/vectors/asthma_vector.png
    - assets/vectors/blue_doctors_vector.png
    - assets/vectors/circulatorysys_vector.png
    - assets/vectors/dna_vector.png
    - assets/vectors/infection_vector.png
    - assets/vectors/studycell_vector.png
    - assets/vectors/vaccine_vector.png
    - assets/vectors/biblioteca/human_11061092.png
    - assets/vectors/biblioteca/human_11847175.png
    - assets/vectors/biblioteca/stroke_11916674.png
    - assets/vectors/biblioteca/tissue_11916635.png
    - assets/vectors/secciones/biology.png
    - assets/vectors/secciones/pharynx.png
    - assets/vectors/secciones/pills.png
    - assets/vectors/secciones/torso.png
    - assets/icons/navbar/book.png
    - assets/icons/navbar/home.png
    - assets/icons/navbar/search.png
    - assets/icons/navbar/user.png



  uses-material-design: true

  

